name: "Support Topic Request"
description: "Request a new article on a support topic"
labels: "support topic"
title: "[Support Topic Request] <title>"
body:
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "A short description of the new topic"
    placeholder: |
      This is a request to document the procedure for transferring large datasets...
  validations:
    required: true
- type: textarea
  id: related_to
  attributes:
    label: "Related to"
    description: |
      Links to relevant tickets in Remedyforce, or discussions in Slack, or discussions in Teams
  validations:
    required: false
- type: textarea
  id: existing_resources
  attributes:
    label: "Existing resources"
    description: |
      Links to any existing articles, for example in the [UCL Research Computing Documentation](https://www.rc.ucl.ac.uk/docs/), that partially satisfy this request
  validations:
    required: false
- type: textarea
  id: recommendation
  attributes:
    label: "Recommendation"
    description: "A brief plan for how this request can be fulfilled"
  validations:
    required: false
      
